=== lory105/allStreaming/xml/comments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- comments schema, model "bambole russe" -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://allStreaming.altervista.org"
targetNamespace="http://allStreaming.altervista.org" elementFormDefault="qualified">
	<xsd:element name="collection">
		<xsd:complexType>
		<xsd:sequence  minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="comment">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="idUser" type="xsd:string" />
						<xsd:element name="typeVideo" />
						<xsd:element name="idVideo" type="xsd:string" />
						<xsd:element name="date" type="xsd:dateTime" />
						<xsd:element name="content" type="xsd:string" />
					</xsd:sequence>
					<xsd:attribute name="id" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== lory105/allStreaming/xml/comments.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="comments.xsl"?>
<collection xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://allStreaming.altervista.org" xs:schemaLocation="http://allStreaming.altervista.org comments.xsd">

	<comment id="1">
		<idUser>1</idUser>
		<typeVideo>film</typeVideo>
		<idVideo>2</idVideo>
		<date>20012-04-26T21:32:52</date>
		<content>Un gran bel film!</content>
	</comment>
	<comment id="2">
		<idUser>2</idUser>
		<typeVideo>serie</typeVideo>
		<idVideo>1</idVideo>
		<date>20012-05-26T21:32:52</date>
		<content>bella serie!</content>
	</comment>
	<comment id="3">
		<idUser>2</idUser>
		<typeVideo>serie</typeVideo>
		<idVideo>2</idVideo>
		<date>20012-05-27T21:32:52</date>
		<content>bella!</content>
	</comment>
</collection>
