=== lory105/allStreaming/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- comments schema, model "bambole russe" -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://allStreaming.altervista.org"
targetNamespace="http://allStreaming.altervista.org" elementFormDefault="qualified">
	<xsd:element name="collection">
		<xsd:complexType>
		<xsd:sequence  minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="user">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="name" type="xsd:string" />
						<xsd:element name="surname" type="xsd:string" />
						<xsd:element name="useraname" type="xsd:string" />
						<xsd:element name="password">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:pattern value="[a-zA-Z0-9]"/>
									<xsd:minLength value="6" />
									<xsd:maxLength value="20" />
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element> 
						<xsd:element name="email">
							<xsd:simpleType> 
    							<xsd:restriction base="xsd:string"> 
      								<xsd:pattern value="[^@]+@[^\.]+\..+"/> 
    							</xsd:restriction> 
  							</xsd:simpleType>
  						</xsd:element>
  						<xsd:element name="avatar" type="xsd:string" />
						<xsd:element name="dateRegistration" type="xsd:dateTime" />
  						<xsd:element name="admin" type="xsd:boolean" />
					</xsd:sequence>
					<xsd:attribute name="id" type="xsd:ID"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

<!-- password: sequenza di lettere e num, lunghezza minima 6, lunghezza max 20  -->

=== lory105/allStreaming/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://allStreaming.altervista.org" xs:schemaLocation="http://allStreaming.altervista.org users.xsd" >

	<user id="1">
		<name>Giacomo</name>
		<surname>Zanon</surname>
		<username>jack</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>giacomoz@gmail.com</email>
		<avatar>../avatar/jack.jpg</avatar>
		<dateRegistration>2007-10-26T21:32:52</dateRegistration>
		<admin>false</admin>
	</user>
	<user id="2">
		<name>Luca</name>
		<surname>Marchegiani</surname>
		<username>luck</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>lucas@gmail.com</email>
		<avatar>../avatar/luck.jpg</avatar>
		<dateRegistration>2008-11-26T21:32:52</dateRegistration>
		<admin>false</admin>
	</user>
	
	<user id="4">
		<name>Jacopo</name>
		<surname>Milano</surname>
		<username>becks</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>your@email.com</email>
		<avatar>../avatar/becks.jpg</avatar>
		<dateRegistration>2012-06-05T13:49:54</dateRegistration>
		<admin>false</admin>
	</user>
	<user id="5">
		<name>Alberto</name>
		<surname>Albero</surname>
		<username>tree</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>tree@hotmail.com</email>
		<avatar>../avatar/tree.jpg</avatar>
		<dateRegistration>2012-06-05T14:05:42</dateRegistration>
		<admin>false</admin>
	</user>
	<user id="6">
		<name>Banana</name>
		<surname>Joe</surname>
		<username>bananajoe</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>your@banana.com</email>
		<avatar>../avatar/bananajoe.jpg</avatar>
		<dateRegistration>2012-06-06T07:43:04</dateRegistration>
		<admin>false</admin>
	</user>
		<user id="7">
		<name>Admin</name>
		<surname>Admin</surname>
		<username>admin</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>admin@allstreaming.com</email>
		<avatar>../avatar/admin.jpg</avatar>
		<dateRegistration>2012-06-06T08:43:04</dateRegistration>
		<admin>true</admin>
	</user>
	<user id="8">
		<name>Bruno</name>
		<surname>Rampa</surname>
		<username>brunello</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>bruno.rampa@libero.it</email>
		<avatar>../avatar/brunello.jpg</avatar>
		<dateRegistration>2012-06-13T21:27:26</dateRegistration>
		<admin>false</admin>
	</user>
	
	<user id="9">
		<name>Paolo</name>
		<surname>Bratto</surname>
		<username>bratt</username>
		<password>5f4dcc3b5aa765d61d8327deb882cf99</password>
		<email>bratt@yahoo.it</email>
		<avatar>../avatar/bratt.jpg</avatar>
		<dateRegistration>2012-06-13T21:41:52</dateRegistration>
		<admin>false</admin>
	</user>
	
</collection>
